(define (problem pb14)
  (:domain rush)
  (:requirements :strips :negative-preconditions)
  (:objects 0 1 2 3 4 5 n x a b c d e f g h i j k)
  (:init
    (near 0 1)
    (near 1 0)
    (near 1 2)
    (near 2 1)
    (near 2 3)
    (near 3 2)
    (near 3 4)
    (near 4 3)
    (near 4 5)
    (near 5 4)
    (equal 0 0)
    (equal 1 1)
    (equal 2 2)
    (equal 3 3)
    (equal 4 4)
    (equal 5 5)
    (car x)   (horizontal x 2)
    (car a)   (horizontal a 0)
    (car b)     (vertical b 2)
    (car c)   (horizontal c 1)
    (car d)     (vertical d 0)
    (car e)     (vertical e 1)
    (car f)     (vertical f 4)
    (car g)     (vertical g 5)
    (car h)   (horizontal h 3)
    (car i)     (vertical i 2)
    (car j)   (horizontal j 4)
    (car k)   (horizontal k 5)
    (pos 0 0 a) (pos 1 0 a) (pos 2 0 b) (pos 3 0 n) (pos 4 0 n) (pos 5 0 n)
    (pos 0 1 n) (pos 1 1 n) (pos 2 1 b) (pos 3 1 n) (pos 4 1 c) (pos 5 1 c)
    (pos 0 2 d) (pos 1 2 e) (pos 2 2 x) (pos 3 2 x) (pos 4 2 f) (pos 5 2 g)
    (pos 0 3 d) (pos 1 3 e) (pos 2 3 h) (pos 3 3 h) (pos 4 3 f) (pos 5 3 g)
    (pos 0 4 n) (pos 1 4 n) (pos 2 4 i) (pos 3 4 n) (pos 4 4 j) (pos 5 4 j)
    (pos 0 5 k) (pos 1 5 k) (pos 2 5 i) (pos 3 5 n) (pos 4 5 n) (pos 5 5 n)
  )
  (:goal
    (and (pos 5 2 x))
  )
)