(define (problem pb28)
  (:domain rush)
  (:requirements :strips :negative-preconditions)
  (:objects 0 1 2 3 4 5 n x a b c d e f g o p q r)
  (:init
    (near 0 1)
    (near 1 0)
    (near 1 2)
    (near 2 1)
    (near 2 3)
    (near 3 2)
    (near 3 4)
    (near 4 3)
    (near 4 5)
    (near 5 4)
    (equal 0 0)
    (equal 1 1)
    (equal 2 2)
    (equal 3 3)
    (equal 4 4)
    (equal 5 5)
    (car x)   (horizontal x 2)
    (car a)     (vertical a 3)
    (car b)   (horizontal b 1)
    (car c)     (vertical c 0)
    (car d)     (vertical d 1)
    (car e)   (horizontal e 3)
    (car f)   (horizontal f 5)
    (car g)   (horizontal g 5)
    (truck o) (horizontal o 0)
    (truck p)   (vertical p 2)
    (truck q)   (vertical q 5)
    (truck r) (horizontal r 4)
    (pos 0 0 o) (pos 1 0 o) (pos 2 0 o) (pos 3 0 a) (pos 4 0 n) (pos 5 0 n)
    (pos 0 1 n) (pos 1 1 n) (pos 2 1 p) (pos 3 1 a) (pos 4 1 b) (pos 5 1 b)
    (pos 0 2 x) (pos 1 2 x) (pos 2 2 p) (pos 3 2 n) (pos 4 2 n) (pos 5 2 n)
    (pos 0 3 c) (pos 1 3 d) (pos 2 3 p) (pos 3 3 e) (pos 4 3 e) (pos 5 3 q)
    (pos 0 4 c) (pos 1 4 d) (pos 2 4 r) (pos 3 4 r) (pos 4 4 r) (pos 5 4 q)
    (pos 0 5 f) (pos 1 5 f) (pos 2 5 g) (pos 3 5 g) (pos 4 5 n) (pos 5 5 q)
  )
  (:goal
    (and (pos 5 2 x))
  )
)