(define (problem pb29)
  (:domain rush)
  (:requirements :strips :negative-preconditions)
  (:objects 0 1 2 3 4 5 n x a b c d e f g h o p r)
  (:init
    (near 0 1)
    (near 1 0)
    (near 1 2)
    (near 2 1)
    (near 2 3)
    (near 3 2)
    (near 3 4)
    (near 4 3)
    (near 4 5)
    (near 5 4)
    (equal 0 0)
    (equal 1 1)
    (equal 2 2)
    (equal 3 3)
    (equal 4 4)
    (equal 5 5)
    (car x)   (horizontal x 2)
    (car a)     (vertical a 2)
    (car b)     (vertical b 5)
    (car c)     (vertical c 0)
    (car d)   (horizontal d 3)
    (car e)   (horizontal e 3)
    (car f)   (horizontal f 4)
    (car g)     (vertical g 3)
    (car h)     (vertical h 5)
    (truck o) (horizontal o 0)
    (truck p)   (vertical p 4)
    (truck r) (horizontal r 5)
    (pos 0 0 o) (pos 1 0 o) (pos 2 0 o) (pos 3 0 n) (pos 4 0 p) (pos 5 0 n)
    (pos 0 1 n) (pos 1 1 n) (pos 2 1 a) (pos 3 1 n) (pos 4 1 p) (pos 5 1 n)
    (pos 0 2 x) (pos 1 2 x) (pos 2 2 a) (pos 3 2 n) (pos 4 2 p) (pos 5 2 b)
    (pos 0 3 c) (pos 1 3 d) (pos 2 3 d) (pos 3 3 e) (pos 4 3 e) (pos 5 3 b)
    (pos 0 4 c) (pos 1 4 f) (pos 2 4 f) (pos 3 4 g) (pos 4 4 n) (pos 5 4 h)
    (pos 0 5 r) (pos 1 5 r) (pos 2 5 r) (pos 3 5 g) (pos 4 5 n) (pos 5 5 h)
  )
  (:goal
    (and (pos 5 2 x))
  )
)