(define (problem pb33)
  (:domain rush)
  (:requirements :strips :negative-preconditions)
  (:objects 0 1 2 3 4 5 n x a b d e f g h i p q r)
  (:init
    (near 0 1)
    (near 1 0)
    (near 1 2)
    (near 2 1)
    (near 2 3)
    (near 3 2)
    (near 3 4)
    (near 4 3)
    (near 4 5)
    (near 5 4)
    (equal 0 0)
    (equal 1 1)
    (equal 2 2)
    (equal 3 3)
    (equal 4 4)
    (equal 5 5)
    (car x)   (horizontal x 2)
    (car a)     (vertical a 1)
    (car b)   (horizontal b 0)
    (car d)   (horizontal d 3)
    (car e)   (horizontal e 3)
    (car f)   (horizontal f 4)
    (car g)     (vertical g 3)
    (car h)     (vertical h 4)
    (car i)     (vertical i 0)
    (truck p)   (vertical p 5)
    (truck q) (horizontal q 5)
    (truck r)   (vertical r 2)
    (pos 0 0 n) (pos 1 0 a) (pos 2 0 r) (pos 3 0 n) (pos 4 0 b) (pos 5 0 b)
    (pos 0 1 n) (pos 1 1 a) (pos 2 1 r) (pos 3 1 n) (pos 4 1 n) (pos 5 1 n)
    (pos 0 2 x) (pos 1 2 x) (pos 2 2 r) (pos 3 2 n) (pos 4 2 n) (pos 5 2 n)
    (pos 0 3 i) (pos 1 3 d) (pos 2 3 d) (pos 3 3 e) (pos 4 3 e) (pos 5 3 p)
    (pos 0 4 i) (pos 1 4 f) (pos 2 4 f) (pos 3 4 g) (pos 4 4 h) (pos 5 4 p)
    (pos 0 5 q) (pos 1 5 q) (pos 2 5 q) (pos 3 5 g) (pos 4 5 h) (pos 5 5 p)
  )
  (:goal
    (and (pos 5 2 x))
  )
)