(define (problem pb34)
  (:domain rush)
  (:requirements :strips :negative-preconditions)
  (:objects 0 1 2 3 4 5 n x a b c d e f h i p q r)
  (:init
    (near 0 1)
    (near 1 0)
    (near 1 2)
    (near 2 1)
    (near 2 3)
    (near 3 2)
    (near 3 4)
    (near 4 3)
    (near 4 5)
    (near 5 4)
    (equal 0 0)
    (equal 1 1)
    (equal 2 2)
    (equal 3 3)
    (equal 4 4)
    (equal 5 5)
    (car x)   (horizontal x 2)
    (car a)     (vertical a 0)
    (car b)     (vertical b 3)
    (car c)     (vertical c 4)
    (car d)     (vertical d 3)
    (car e)     (vertical e 2)
    (car f)   (horizontal f 4)
    (car h)   (horizontal h 5)
    (car i)   (horizontal i 5)
    (truck p)   (vertical p 5)
    (truck q) (horizontal q 3)
    (truck r) (horizontal r 0)
    (pos 0 0 a) (pos 1 0 n) (pos 2 0 n) (pos 3 0 r) (pos 4 0 r) (pos 5 0 r)
    (pos 0 1 a) (pos 1 1 n) (pos 2 1 n) (pos 3 1 b) (pos 4 1 n) (pos 5 1 p)
    (pos 0 2 x) (pos 1 2 x) (pos 2 2 n) (pos 3 2 b) (pos 4 2 c) (pos 5 2 p)
    (pos 0 3 q) (pos 1 3 q) (pos 2 3 q) (pos 3 3 d) (pos 4 3 c) (pos 5 3 p)
    (pos 0 4 n) (pos 1 4 n) (pos 2 4 e) (pos 3 4 d) (pos 4 4 f) (pos 5 4 f)
    (pos 0 5 i) (pos 1 5 i) (pos 2 5 e) (pos 3 5 h) (pos 4 5 h) (pos 5 5 n)
  )
  (:goal
    (and (pos 5 2 x))
  )
)