(define (problem pb36)
  (:domain rush)
  (:requirements :strips :negative-preconditions)
  (:objects 0 1 2 3 4 5 n x a b c d e f g o p q r)
  (:init
    (near 0 1)
    (near 1 0)
    (near 1 2)
    (near 2 1)
    (near 2 3)
    (near 3 2)
    (near 3 4)
    (near 4 3)
    (near 4 5)
    (near 5 4)
    (equal 0 0)
    (equal 1 1)
    (equal 2 2)
    (equal 3 3)
    (equal 4 4)
    (equal 5 5)
    (car x)   (horizontal x 2)
    (car a)   (horizontal a 0)
    (car b)     (vertical b 1)
    (car c)   (horizontal c 1)
    (car d)     (vertical d 3)
    (car e)     (vertical e 2)
    (car f)   (horizontal f 4)
    (car g)   (horizontal g 5)
    (truck o)   (vertical o 0)
    (truck p) (horizontal p 0)
    (truck q)   (vertical q 5)
    (truck r) (horizontal r 3)
    (pos 0 0 o) (pos 1 0 p) (pos 2 0 p) (pos 3 0 p) (pos 4 0 a) (pos 5 0 a)
    (pos 0 1 o) (pos 1 1 b) (pos 2 1 c) (pos 3 1 c) (pos 4 1 n) (pos 5 1 q)
    (pos 0 2 o) (pos 1 2 b) (pos 2 2 x) (pos 3 2 x) (pos 4 2 n) (pos 5 2 q)
    (pos 0 3 r) (pos 1 3 r) (pos 2 3 r) (pos 3 3 d) (pos 4 3 n) (pos 5 3 q)
    (pos 0 4 n) (pos 1 4 n) (pos 2 4 e) (pos 3 4 d) (pos 4 4 f) (pos 5 4 f)
    (pos 0 5 g) (pos 1 5 g) (pos 2 5 e) (pos 3 5 n) (pos 4 5 n) (pos 5 5 n)
  )
  (:goal
    (and (pos 5 2 x))
  )
)