(define (problem pb40)
  (:domain rush)
  (:requirements :strips :negative-preconditions)
  (:objects 0 1 2 3 4 5 n x a b c d e f g h i o p q)
  (:init
    (near 0 1)
    (near 1 0)
    (near 1 2)
    (near 2 1)
    (near 2 3)
    (near 3 2)
    (near 3 4)
    (near 4 3)
    (near 4 5)
    (near 5 4)
    (equal 0 0)
    (equal 1 1)
    (equal 2 2)
    (equal 3 3)
    (equal 4 4)
    (equal 5 5)
    (car x)   (horizontal x 2)
    (car a)   (horizontal a 0)
    (car b)     (vertical b 4)
    (car c)     (vertical c 1)
    (car d)     (vertical d 2)
    (car e)     (vertical e 3)
    (car f)     (vertical f 2)
    (car g)   (horizontal g 4)
    (car h)   (horizontal h 5)
    (car i)   (horizontal i 5)
    (truck o)   (vertical o 0)
    (truck p)   (vertical p 5)
    (truck q) (horizontal q 3)
    (pos 0 0 o) (pos 1 0 a) (pos 2 0 a) (pos 3 0 n) (pos 4 0 b) (pos 5 0 n)
    (pos 0 1 o) (pos 1 1 c) (pos 2 1 d) (pos 3 1 n) (pos 4 1 b) (pos 5 1 p)
    (pos 0 2 o) (pos 1 2 c) (pos 2 2 d) (pos 3 2 x) (pos 4 2 x) (pos 5 2 p)
    (pos 0 3 q) (pos 1 3 q) (pos 2 3 q) (pos 3 3 e) (pos 4 3 n) (pos 5 3 p)
    (pos 0 4 n) (pos 1 4 n) (pos 2 4 f) (pos 3 4 e) (pos 4 4 g) (pos 5 4 g)
    (pos 0 5 h) (pos 1 5 h) (pos 2 5 f) (pos 3 5 i) (pos 4 5 i) (pos 5 5 n)
  )
  (:goal
    (and (pos 5 2 x))
  )
)