(define (problem pbp41)
  (:domain rush)
  (:requirements :strips :negative-preconditions)
  (:objects p0 p1 p2 p3 p4 p5 n x a b c d e f g h i o p q)
  (:init
    (near p0 p1)
    (near p1 p0)
    (near p1 p2)
    (near p2 p1)
    (near p2 p3)
    (near p3 p2)
    (near p3 p4)
    (near p4 p3)
    (near p4 p5)
    (near p5 p4)
    (equal p0 p0)
    (equal p1 p1)
    (equal p2 p2)
    (equal p3 p3)
    (equal p4 p4)
    (equal p5 p5)
    (car x)   (horizontal x p2)
    (car a)     (vertical a p3)
    (car b)   (horizontal b p1)
    (car c)     (vertical c p0)
    (car d)   (horizontal d p3)
    (car e)     (vertical e p2)
    (car f)     (vertical f p1)
    (car g)   (horizontal g p5)
    (car h)   (horizontal h p5)
    (car i)   (horizontal i p4)
    (truck o)   (vertical o p4)
    (truck p)   (vertical p p5)
    (truck q) (horizontal q p0)
    (pos p0 p0 q) (pos p1 p0 q) (pos p2 p0 q) (pos p3 p0 a) (pos p4 p0 o) (pos p5 p0 p)
    (pos p0 p1 c) (pos p1 p1 b) (pos p2 p1 b) (pos p3 p1 a) (pos p4 p1 o) (pos p5 p1 p)
    (pos p0 p2 c) (pos p1 p2 n) (pos p2 p2 x) (pos p3 p2 x) (pos p4 p2 o) (pos p5 p2 p)
    (pos p0 p3 d) (pos p1 p3 d) (pos p2 p3 e) (pos p3 p3 n) (pos p4 p3 n) (pos p5 p3 n)
    (pos p0 p4 n) (pos p1 p4 f) (pos p2 p4 e) (pos p3 p4 n) (pos p4 p4 i) (pos p5 p4 i)
    (pos p0 p5 n) (pos p1 p5 f) (pos p2 p5 g) (pos p3 p5 g) (pos p4 p5 h) (pos p5 p5 h)
  )
  (:goal
    (and (pos p5 p2 x))
  )
)