(define (problem pb9)
  (:domain aperture)
  (:objects
    pbody - robot
    h1 h2 h3 h4 h5 h6 h7 - hallway
    r1 r2 r3 r4 - room
    c1 c2 c3 - cube
    red yellow - color
  )
  (:init
    (at pbody r2)
    (dropped c1 h1)
    (dropped c2 h6)
    (dropped c3 h2)
    (connected h1 r1)
    (connected r1 h1)
    (connected r1 h2)
    (connected h2 r1)
    (connected h2 h5)
    (connected h5 h2)
    (connected h5 r2)
    (connected r2 h5)
    (connected h2 r2)
    (connected r2 h4)
    (connected h4 r2)
    (connected h4 h3)
    (connected h3 h4)
    (connected h3 r3)
    (connected r3 h3)
    (connected h5 h7)
    (connected h7 h5)
    (connected h7 h6)
    (connected h6 h7)
    (connected h6 r4)
    (connected r4 h4)
    (connected h4 r4)
    (ammo pbody red)
    (ammo pbody yellow)
    (portal red yellow)
    (portal yellow red)
    (marked red r4)
    (marked yellow r4)
    (flatwall h1)
    (flatwall h5)
    (flatwall h6)
    (flatwall r3)
  )
  (:goal
    (and
      (at pbody r3)
      (dropped c1 r3)
      (dropped c2 r3)
      (dropped c3 r3)
    )
  )
)
